### ISSUE TITLE
gives me parse error: invalid numeric literal at line 1 column 7 

### ISSUE THREAD

**Issue by ghost** [endtest-technologies/github-run-tests-action#3]
when i run this it gives me an error invalid numeric literal at line 1 column 7.need solution.

[removed image]

**Comment by liviulupei** [comment]
Hi, @tayyabejaz1 
Please send us that Endtest API request in an email to contact@endtest.io and we'll reply there.
Since the Endtest API request can contain sensitive information, we cannot discuss those details here. 
The issue is not happening for other users, so I'm assuming there's something wrong in your Endtest API request.

**Comment by liviulupei** [comment]
**Solution:**

Make sure to use at least version 1.8 of our Endtest Github Action:

_uses: endtest-technologies/github-run-tests-action@v1.8_
